#!/bin/bash --login
#$ -cwd                   # Run job from directory where submitted

# If running on a GPU, add:
#$ -l v100=1

#$ -pe smp.pe 8          # Number of cores on a single compute node. GPU jobs can
                         # use up to 8 cores per GPU.

# We now recommend loading the modulefile in the jobscript
module load apps/binapps/pytorch/1.11.0-39-gpu

# $NSLOTS is automatically set to the number of cores requested on the pe line.
# Inform some of the python libraries how many cores we can use.
export OMP_NUM_THREADS=$NSLOTS

# get arguments

# model
model=$1

# task
task=$2

# directory name
directory=$3

# etc
etc=$4

python3 /mnt/iusers01/fse-ugpgt01/compsci01/y44694jk/project/main.py $model $task $directory $etc
